render:
  resolution:
    width: 1920
    height: 1080
  fov: 75
  fov_type: vertical  # options: vertical, horizontal
  radius: 1.5
  height: 1.0
  num_views: 6
  up_vector: [0, 0, 1]
  output_folder: output

keyframe:
  num_frames: 6
  blur_threshold: 150.0
  voxel_size: 0.02
  kmeans_n_init: 10
  kmeans_max_iter: 300
  kmeans_tol: 1e-4

paths:
  base_data_dir: data
  dataset_path: data/scans
  annotations_file: data/results/scannet_annotations.json
  uninterpretable_file: data/results/uninterpretable_images.json
  camera_pose_file: camera_pose.json
  download_script: scripts/download_subset.sh

download:
  label_map_filename: scannetv2-labels.combined.tsv
  file_types:
    - "_vh_clean_2.ply"
    - "_vh_clean_2.labels.ply"
    - "_vh_clean_2.0.010000.segs.json"
    - ".aggregation.json"
    - ".txt"
    - ".sens"

ui:
  sample_scene: scene0000_00
  sample_view: view_1
  sample_description: >
    A studio apartment On the left, there's a bed with blue bedding next to a worn rug and a wooden desk. A bicycle leans against a corrugated metal wall near the center, beside a dark L-shaped sofa with pillows and two ottomans in front. To the right, there's a small table or counter with stools. The bicycle is placed next to the TV cabinet, the TV is facing the shorter side of the L-shaped sofa.
  